name: navigation
version: 0.0.1
publish_to: none
description: Project navigation module

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 7.8.3

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: 2.4.11

  flutter_lints: 4.0.0
  analyzer: 6.4.1

  core:
    path: ../core

flutter:
  generate: true
