name: home
description: "Home package."
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  navigation:
    path: ../../navigation
  settings:
    path: ../settings
  profile:
    path: ../profile
  scanner:
    path: ../scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: 2.4.11

  flutter_lints: 4.0.0
  analyzer: 6.4.1

flutter:
  generate: true
