name: keeper

packages:
  - core
  - core_ui
  - data
  - domain
  - navigation
  - feature/home
  - feature/profile
  - feature/scanner
  - feature/settings

scripts:
  clean:
    flutter clean &&
    melos clean

  bootstrap:
    flutter pub get &&
    melos bootstrap

  setup:
    melos run bootstrap &&
    melos run generate_localization &&
    melos run build_runner

  build_runner:
    melos exec --scope="data" -- dart run build_runner build --delete-conflicting-outputs &&
    melos exec --scope="navigation" -- dart run build_runner build --delete-conflicting-outputs &&
    melos exec --scope="feature/*" -- dart run build_runner build --delete-conflicting-outputs

  generate_localization:
    melos exec --scope="core" -- flutter pub run easy_localization:generate -h &&
    melos exec --scope="core" -- dart run easy_localization:generate -f keys -o locale_keys.g.dart -O lib/src/localization/generated -S resources/lang
