name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0
  equatable: 2.0.5
  get_it: 8.0.0
  dio: 5.7.0
  logger: 2.4.0
  flutter_bloc: 8.1.6
  hive: 2.2.3
  shared_preferences: 2.3.0

  keeper:
    path: ../
  navigation:
    path: ../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0
  analyzer: 6.4.1
  build_runner: 2.4.11
  build_resolvers: 2.4.2
  hive_generator: 2.0.1

flutter:
  generate: true

