name: domain
version: 0.0.1
publish_to: none
description: Project domain module

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0
  analyzer: 6.4.1

  core:
    path: ../core

flutter:
  generate: true
