name: core_ui
version: 0.0.1
publish_to: none
description: Project core_ui module

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0
  analyzer: 6.4.1

flutter:
  generate: true

